name: Deploy Workflow Azure
on: [push]
env:
  NODE_VERSION: "16.x"
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Install Dependencies"
        run: npm install
      - name: "Run Jest"
        run: npm run test
      - name: "Run Linter"
        run: npm run linter