name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    node-version: 16.x
    steps:
    - uses: actions/checkout@v2
    - name: Run Jest
      run: npm test